import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <title>Function.Guide</title>
      <meta name="viewport" content="initial-scale=1, maximum-scale=1" />
      <body>{children}</body>
    </html>
  )
}
